#!/bin/bash  

function usage {
    echo "Usage: $(basename $0) [version] [revision]" >&2
}

[ "$1" ] || { echo Which version? >&2; usage; exit 1; }
version=$1

[ "$2" ] || { echo Which package revision? >&2; usage; exit 1; }
revision=$2

pushd "$(dirname "$0")" > /dev/null

echo -n "Adjust package changelog? [Y/n]           "
read -n1 answer
if [[ "$anwser" =~ ^[^n]$ ]]; then
    vim debian/changelog
    exit
fi
echo

function inject_version {
    echo Injecting version
    for file in $@; do
        sed -i "s/{VERSION}/$version/g" $file
    done
}

function inject_date {
    echo Injecting current datetime
    datetime=$(LC_ALL=en_US.utf8 date "+%a, %d %b %Y %H:%M:%S")
    for file in $@; do
        sed -i "s/{DATETIME}/$datetime/g" $file
    done
}

function inject_revision {
    echo Injecting revision
    for file in $@; do
        sed -i "s/{REVISION}/$revision/g" $file
    done
}

function inject_current_year {
    for file in $@; do
        year=$(date "+%Y")
        sed -i "s/{YEAR}/$year/g" $file
    done
}

mkdir sodalite-$version-$revision
pushd sodalite-$version-$revision > /dev/null

echo Downloading source tarball
tarball=v${version}.tar.gz
url="https://github.com/hnicke/sodalite/archive/$tarball"
#url="https://github.com/hnicke/sodalite/archive/master.tar.gz"
wget -q --show-progress "$url" -O $tarball ||
     { echo Target not found: $url >&2; exit; }


echo Extracting tarball
tar -xf $tarball
mv $tarball sodalite_$version.orig.tar.gz

sources=sodalite-$version
#sources=sodalite-master

echo Adding debian directory
cp -r ../debian $sources

pushd $sources> /dev/null
inject_version debian/{changelog,control}
inject_date debian/changelog
inject_revision debian/changelog
inject_current_year debian/copyright

echo Building deb package
dpkg-buildpackage -b

popd > /dev/null

rm -rf $sources
popd > /dev/null
popd > /dev/null
